export const ADD_TO_CART='ADD_TO_CART';
export const CARD_MINI_DETAIL='CARD_MINI_DETAIL';
export const CARD_COMPLETE_DETAIL='CARD_COMPLETE_DETAIL';
export const REMOVE_CARD='REMOVE_CARD';
export const CHANGE_QUANTITY_VALUE='CHANGE_QUANTITY_VALUE';